### ISSUE TITLE
Labels should support arbitrary tree hierarchies

### ISSUE THREAD

**Issue by jimbaker** [rackerlabs/craton#110]
We should use materialized paths to make such lookups efficient, at minor cost for updates.

Variables overrides should chain with respect to such hierarchies.

Such support allows for mapping network device topologies, so long as they are strict trees. However, a device will continue to have support for multiple labels, which should give us most of the benefits of arbitrary DAGs without having to compute potentially expensive transitive closures.

**Comment by sulochan** [comment]
+1 very useful feature to have.

**Comment by sulochan** [comment]
https://bugs.launchpad.net/craton/+bug/1606868
