### ISSUE TITLE
Models: UUID field should be string (36) since we are not using it as primarykey

### ISSUE THREAD

**Issue by sulochan** [rackerlabs/craton#43]
So UUID filed currently is types.BINARY(16) which is the default for sqlalchemy, but we are not using UUID for primary anymore and should just save uuid's as string(36) rather ? sqlalchemy utils can also do char(32) but I think the preferred way should be to store with dash as string(36) ?

Just opening this issue to see what others think about this ? I have mostly seen openstack projects go with string(36) but maybe some do use char(32) or binary ?

**Comment by sorrison** [comment]
I vote to do the same as other projects like nova and go for a char 36.  Using binary uuid is only useful on Postgres at this stage I believe.

**Comment by jimbaker** [comment]
We are using SQLAlchemy-Utils and its collection of custom types. In particular, [UUIDType](https://sqlalchemy-utils.readthedocs.io/en/latest/data_types.html#module-sqlalchemy_utils.types.uuid ) works as follows:

> Stores a UUID in the database natively when it can and falls back to a BINARY(16) or a CHAR(32) when it can’t.

**Comment by jimbaker** [comment]
The other relevant consideration is that this is mapped into Python as an [UUID object](https://docs.python.org/2/library/uuid.html); so you can do stuff like the following:

```
>>> str(host.project.id)
'96c2fce3-13bd-11e6-af29-6c40089bf700'
```

and it just works, which is great for output to external systems as strings. This includes being able to read in UUIDs - the UUID constructor works, dashes or not:

```
>>> from uuid import UUID
>>> x = UUID('96c2fce3-13bd-11e6-af29-6c40089bf700')
>>> x
UUID('96c2fce3-13bd-11e6-af29-6c40089bf700')
```

And of course if you try to use a bad UUID string to construct an UUID object, that works as well:

```
>>> x = UUID('cafe-9999')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/uuid.py", line 134, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
```

**Comment by sorrison** [comment]
I like the idea of the UUID field too however the issue I had with these is that if you use the mysql client to inspect the DB you get binary for UUID which makes it impossible to use if you need to do some sql query. Also it's different to what all the other openstack projects do. 

I got a change through for gonocchi that changed this there too https://github.com/openstack/gnocchi/commit/d4f87da5d8cfce2cdab7f6dbdcc9748783f29ccd

**Comment by jimbaker** [comment]
Conclusion in today's tech team meeting: eliminate this use of UUID in favor of small integer primary keys. UUIDs are very useful, just not in this modeling usage. This also simplifies it even further for Sam's use case.

**Comment by sorrison** [comment]
+1
