### ISSUE TITLE
Python API for ingest, with test data from OSIC reference cluster

### ISSUE THREAD

**Issue by b3rnard0** [rackerlabs/craton#51]
Python API to ingest inventory data from Ansible configuration.

We will  verify with actual ingest from [OSIC configuration](https://github.com/os-cloud/osic-ref-impl)

**Comment by sigmavirus24** [comment]
Do we need https://github.com/osic/ref-impl ?

**Comment by sulochan** [comment]
NO NEED TO MOVE TO LP.
