### ISSUE TITLE
Inventory Dashboard

### ISSUE THREAD

**Issue by b3rnard0** [rackerlabs/craton#52]
Using Flask, build out a dashboard against the inventory database.

Initially this can be read only. It should display the inventory hierarchy; and be able to drill down to variables (ideally showing how the variable has been defined).

Additions over time, but outside the scope of this initial card:
* User can update inventory in the dashboard
* Display corresponding workflows ("cloud progress bar")
* Schedule workflows to be performed

**Comment by jimbaker** [comment]
Initially this can be read only. It should display the inventory hierarchy; and be able to drill down to variables (ideally showing how the variable has been defined).

Additions over time, but outside the scope of this initial card:
* User can update inventory in the dashboard
* Display corresponding workflows ("cloud progress bar")
* Schedule workflows to be performed

**Comment by sulochan** [comment]
THIS WE DONT TRACK HERE, THIS IS GOING OVER TO HORIZON.
