### ISSUE TITLE
Update completely outdated README.rst

### ISSUE THREAD

**Issue by jimbaker** [rackerlabs/craton#64]
Should provide a brief overview, then point to user stories, design documents, and other docs. Currently the README reflects team's decisions from a couple of months back, and it is very much out of date.

**Comment by sulochan** [comment]
So i want to suggest a few things here.
1. Let get a wiki going so we can put thing in much details there.
2. Let trim the readme to something that is shot but give a nice overview.
3. Lets not put too much emphasis on Ansible, as that is not the only consumer we have of this service (in particular of inventory service).

**Comment by jimbaker** [comment]
+1, agreed
