### ISSUE TITLE
Model configurable devices in inventory, not just hosts

### ISSUE THREAD

**Issue by jimbaker** [rackerlabs/craton#65]
The current inventory model only supports SSH-addressable hosts (using `Host`). Let's instead change this such that we have a base configurable `Device` class, which represents all physical devices that can in fact be configured. (This separates out other assets such as hard disks - discoverable, etc, but not configurable in their own right.)

Such modeling will enable us to support network and storage devices that are only indirectly configurable via tooling like Ansible. It should also better support integration with third party asset management systems like OneOps and Rackspace Core.

We will use [joined table inheritance](http://docs.sqlalchemy.org/en/latest/orm/inheritance.html#joined-table-inheritance), along with a discriminant `type` column, to implement inheritance. `Host` differs from `Device` in that it adds ssh keys support via a relation to `AccessSecret`.

For the case of OneOps, this separation will simplify joining together information that is managed by its component instance model, with what Craton manages; while still enabling same database integration via using a custom mapper.

**Comment by sulochan** [comment]
+1
