### ISSUE TITLE
Create python/REST api for project and user

### ISSUE THREAD

**Issue by sulochan** [rackerlabs/craton#86]
Its missing now .. this is for post mvp.

**Comment by sulochan** [comment]
So here is the problem with this:
1. We need an API for creating projects and users.
2. We cant have an API without a project and an admin user that can create other projects/users.

Possible solutions:
A. Creating an initial Admin project and Admin user is a part of the install process. This will be the step after creating the craton db in mysql. After than we can use that credential to create other projects and users etc. Each project admin will have permission to create users under his own project.

B. Let leave the project and user creation to the end user. i.e : users will manually insert db rows for projects and user.

**Comment by jimbaker** [comment]
Solution (A) solves the bootstrapping problem. Let's use cryptographically secure credentials for the admin user, and report back via the install script.

re (B) - even in the simplest case where operators do not want to use Keystone, they still will want some user management, with corresponding APIs. Also using the database directly violates the abstraction we want to provide over it.

**Comment by sigmavirus24** [comment]
Keystone has a way of bootstrapping keystone with an admin token and admin username, so A is at least backed by precedent.

**Comment by mwturvey** [comment]
I also don't like the idea of forcing the user to access the db directly.  They shouldn't have to know about its format (even if most will).  

One thing I'd add is that even if we go the route of A, we need a way of allowing the user to reset the  admin password if it is forgotten/ lost etc.  This means that in addition to an install-time setup, there would need to be some sort of a run-time way of resetting the admin password.  I'd think that it could be by launching one of the craton scripts with a special command-line "reset" switch.

**Comment by sulochan** [comment]
this has been moved over to launchpad. closing here.
